// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1aLhiWUZGEQtM5U9rWhpZmmGSGPsG-qc',
    appId: '1:114596867965:web:d94cb0b22259fdac70a614',
    messagingSenderId: '114596867965',
    projectId: 'citizen-report-incident',
    authDomain: 'citizen-report-incident.firebaseapp.com',
    storageBucket: 'citizen-report-incident.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqNce17eeKb3JS1aw8jn91xEx_SrM-h94',
    appId: '1:114596867965:android:b2f67f033b3a6f1d70a614',
    messagingSenderId: '114596867965',
    projectId: 'citizen-report-incident',
    storageBucket: 'citizen-report-incident.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1aABL18ggAPf6St6UVcIaTb8NK2nHn4',
    appId: '1:114596867965:ios:51366d2312d704fe70a614',
    messagingSenderId: '114596867965',
    projectId: 'citizen-report-incident',
    storageBucket: 'citizen-report-incident.firebasestorage.app',
    iosBundleId: 'com.example.citizenReportIncident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1aABL18ggAPf6St6UVcIaTb8NK2nHn4',
    appId: '1:114596867965:ios:51366d2312d704fe70a614',
    messagingSenderId: '114596867965',
    projectId: 'citizen-report-incident',
    storageBucket: 'citizen-report-incident.firebasestorage.app',
    iosBundleId: 'com.example.citizenReportIncident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1aLhiWUZGEQtM5U9rWhpZmmGSGPsG-qc',
    appId: '1:114596867965:web:59b695499466de5670a614',
    messagingSenderId: '114596867965',
    projectId: 'citizen-report-incident',
    authDomain: 'citizen-report-incident.firebaseapp.com',
    storageBucket: 'citizen-report-incident.firebasestorage.app',
  );
}
